import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @inlang/paraglide-js (scripts/paraglide-compile.mjs).
    // File-per-message + `/* eslint-disable */` headers — do not lint, không có
    // giá trị sửa tay vì sẽ bị overwrite ở compile tiếp theo.
    "src/paraglide/**",
  ]),
]);

export default eslintConfig;
